{
 "title": "Node performance - summary",
 "tags": [ "node" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(up{job=\"node\"},environment)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(up{job=\"node\",environment=~\"$environment\"}, role)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"node\",environment=~\"$environment\",role=~\"$role\"},instance)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "fqdn",
    "label": "FQDN",
    "query": "label_values(up{instance=\"$instance\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node CPU Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count (count by (cpu) (node_cpu_seconds_total{instance=\"$instance\"}))"
    }
   ]
  },
  {
   "title": "CPU core seconds per mode",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (rate(node_cpu_seconds_total{instance=\"$instance\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Node Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "RAM"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "Memory - active / inactive",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"$instance\"}",
     "legendFormat": "active"
    },
    {
     "expr": "node_memory_Inactive_bytes{instance=\"$instance\"}",
     "legendFormat": "inactive"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$instance\"}",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Paging and swap activity",
   "type": "graph",
   "description": "Paging: Fine-grain copying of pages in the address space. Common in normal operation.\n\n- pgpgin: Number of kilobytes the system has paged in from disk per second.\n\n- pgpgout: Number of kilobytes the system has paged out to disk per second.\n\nSwapping: Copying the entire address space of a process to and from the swap device. This is an indicator of memory pressure.\n\n- pswpin: Number of kilobytes the system has swapped in from disk per second.\n\n- pswpout: Number of kilobytes the system has swapped out to disk per second.",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgpgin{instance=\"$instance\"}[$interval])",
     "legendFormat": "pgpgin"
    },
    {
     "expr": "rate(node_vmstat_pgpgout{instance=\"$instance\"}[$interval])",
     "legendFormat": "pgpgout"
    },
    {
     "expr": "rate(node_vmstat_pswpin{instance=\"$instance\"}[$interval])",
     "legendFormat": "pgswpin"
    },
    {
     "expr": "rate(node_vmstat_pswpout{instance=\"$instance\"}[$interval])",
     "legendFormat": "pgswpout"
    }
   ]
  },
  {
   "title": "Swap availability",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "node_memory_SwapFree_bytes{instance=\"$instance\"}",
     "legendFormat": "free"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Network traffic - octets receive/transmit",
   "type": "graph",
   "description": "Traffic in octets per second.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps", "label": "octets per second" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$instance\",device!=\"lo\"}[$interval])",
     "legendFormat": "{{ device}} receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$instance\",device!=\"lo\"}[$interval])",
     "legendFormat": "{{ device}} transmit"
    }
   ]
  },
  {
   "title": "Network saturation",
   "type": "gauge",
   "description": "Saturation value set to 300 Mbit per second.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$instance\",device!=\"lo\"}[$interval]) * 8",
     "legendFormat": "{{ device}} transmit"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$instance\",device!=\"lo\"}[$interval]) * 8",
     "legendFormat": "{{ device}} receive"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_errs_total{instance=\"$instance\",device!=\"lo\"}[$interval])",
     "legendFormat": "{{ device }} transmit"
    },
    {
     "expr": "rate(node_network_receive_errs_total{instance=\"$instance\",device!=\"lo\"}[$interval])",
     "legendFormat": "{{ device }} receive"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Disk traffic - read IO operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk saturation - IO time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk latency - read operations",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=\"$instance\"}[$interval]) / rate(node_disk_reads_completed_total{instance=\"$instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Disk errors per filsystems",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_filesystem_device_error{instance=\"$instance\",device!=\"tmpfs\"}[$interval])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk traffic - write IO operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk latency - write operations",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=\"$instance\"}[$interval]) / rate(node_disk_writes_completed_total{instance=\"$instance\"}[$interval])"
    }
   ]
  }
 ]
}