{
 "title": "Node performance - disk",
 "tags": [ "node" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(up{job=\"node\"},environment)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(up{job=\"node\",environment=~\"$environment\"}, role)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"node\",environment=~\"$environment\",role=~\"$role\"},instance)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "fqdn",
    "label": "FQDN",
    "query": "label_values(up{instance=\"$instance\"}, instance)"
   },
   {
    "name": "device",
    "query": "label_values(node_disk_io_time_seconds_total{instance=\"$instance\"},device)"
   }
  ]
 },
 "panels": [
  {
   "title": "IO Wait percentage per CPU core ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"iowait\",instance=\"$instance\"}[$interval])",
     "legendFormat": "cpu{{ cpu }}"
    }
   ]
  },
  { "title": "Device $device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "device" },
  {
   "title": "Disk traffic - read IO operations for $fqdn",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"$instance\",device=\"$device\"}[$interval])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk saturation - IO time for $fqdn",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$instance\",device=\"$device\"}[$interval])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk latency - read operations",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=\"$instance\",device=\"$device\"}[$interval]) / rate(node_disk_reads_completed_total[$interval])"
    }
   ]
  },
  {
   "title": "IO size - bytes per completed read",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\",device=\"$device\"}[$interval]) / irate(node_disk_reads_completed_total[$interval])"
    }
   ]
  },
  {
   "title": "Disk traffic - write IO operations for $fqdn",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"$instance\",device=\"$device\"}[$interval])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk errors - filsystems for $fqdn",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_filesystem_device_error{instance=\"$instance\",device=~\".+${device}[0-9]+\"}[$interval])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk latency - write operations",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=\"$instance\",device=\"$device\"}[$interval]) / rate(node_disk_writes_completed_total[$interval])"
    }
   ]
  },
  {
   "title": "IO size - bytes per completed write",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\",device=\"$device\"}[$interval]) / irate(node_disk_writes_completed_total[$interval])"
    }
   ]
  }
 ]
}